version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classworks
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=
    volumes:
      - .data:/app/data

